### PR TITLE
Make API Changes compatible with Flutter 3.22.0

### PR DESCRIPTION
**Pull request by gdelataillade**
Update deprecated code:
CleanShot 2024-05-14 at 17 37 19@2x

### Flutter 3.22:
https://docs.flutter.dev/release/release-notes/release-notes-3.22.0

### CODE REVIEW

**Comment by gdelataillade** [comment]
Finally, I updated the Github Action `flutter_format.yaml`, which was using the deprecated `flutter format` command. [Details here](https://github.com/flutter/flutter/issues/115809).

**Comment by yelkamel** [comment]
This is need to be merged

**Comment by redguitars97** [comment]
Please, can someone approve this merge request? 

Thanks and best regards, Mattia.

**Comment by juliansteenbakker** [comment]
Thanks for the fix! I will update the package asap

**Pull request merged**
